# Generated by Django 5.1.1 on 2025-01-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=100)),
                ('artistname', models.CharField(max_length=100)),
                ('muiscdirector', models.CharField(max_length=100)),
                ('musicproducer', models.CharField(max_length=100)),
                ('songs', models.ImageField(default='Sample.mp3', upload_to='albums')),
            ],
        ),
    ]
