# Generated by Django 5.1.1 on 2025-01-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
