# Generated by Django 5.1.1 on 2025-01-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_music_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='muiscdirector',
            new_name='musicdirector',
        ),
    ]
