# Generated by Django 5.1.1 on 2025-01-30 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_muiscdirector_music_musicdirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50)),
                ('image', models.ImageField(default='Sample.jpg', upload_to='profiles')),
            ],
        ),
    ]
