# Generated by Django 5.1.1 on 2025-01-30 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='genre_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.genre'),
        ),
    ]
