# Generated by Django 5.1.1 on 2025-02-10 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_music_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='lyrics',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
