# Generated by Django 5.1.1 on 2025-02-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_music_lyrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
