# Generated by Django 5.1.1 on 2025-02-21 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
