# Generated by Django 5.1.1 on 2025-02-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='songs',
            field=models.FileField(default='Sample.mp3', upload_to='albums'),
        ),
    ]
