# Generated by Django 5.1.1 on 2025-03-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_music_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='like',
        ),
    ]
