# Generated by Django 5.1.1 on 2025-03-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_remove_music_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
