# Generated by Django 5.1.1 on 2025-01-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Music',
            new_name='User',
        ),
    ]
