# Generated by Django 5.1.1 on 2025-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(default='Sample.jpg', upload_to='profiles')),
            ],
        ),
    ]
