# Generated by Django 5.1.1 on 2025-02-11 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
