# Generated by Django 5.1.1 on 2025-02-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50)),
                ('image', models.ImageField(default='Sample.jpg', upload_to='profiles')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
