# Generated by Django 5.1.1 on 2025-02-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
