# Generated by Django 5.1.1 on 2025-02-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
    ]
