# Generated by Django 5.1.1 on 2025-02-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comments', models.CharField(max_length=50)),
            ],
        ),
    ]
