# Generated by Django 5.1.1 on 2025-02-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
