# Generated by Django 5.1.1 on 2025-02-24 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_delete_comment'),
        ('User', '0012_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=50)),
                ('music', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.music')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.register')),
            ],
        ),
    ]
