# Generated by Django 5.1.1 on 2025-02-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_comment_created_at_alter_comment_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
