# Generated by Django 5.1.1 on 2025-02-25 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0016_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='firstname',
        ),
    ]
