# Generated by Django 5.1.1 on 2025-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0017_rename_name_comment_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musicname', models.CharField(max_length=255)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
