# Generated by Django 5.1.1 on 2025-03-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_like_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
