# Generated by Django 5.1.1 on 2025-03-04 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_music_dislikes_music_likes'),
        ('User', '0021_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.register')),
            ],
        ),
    ]
