# Generated by Django 5.1.1 on 2025-03-10 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0022_favour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
