# Generated by Django 5.1.1 on 2025-03-11 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0023_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
