# Generated by Django 5.1.1 on 2025-03-12 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0026_subcription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcription',
        ),
    ]
