# Generated by Django 5.1.1 on 2025-03-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0028_subcription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcription',
            name='user',
        ),
    ]
