# Generated by Django 5.1.1 on 2025-03-12 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0029_remove_subcription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.register'),
        ),
    ]
