# Generated by Django 5.1.1 on 2025-03-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_subcription_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcription',
            name='duration_days',
            field=models.IntegerField(null=True),
        ),
    ]
