# Generated by Django 5.1.1 on 2025-03-13 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_subcription_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subcription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subcription',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='subcription',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='subcription',
            name='user',
        ),
        migrations.AddField(
            model_name='subcription',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Usersub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.register')),
            ],
        ),
    ]
