# Generated by Django 5.1.1 on 2025-03-13 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0032_remove_subcription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersub',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usersub',
            name='plan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.subcription'),
        ),
    ]
