# Generated by Django 5.1.1 on 2025-03-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0033_remove_usersub_is_active_usersub_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersub',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
