# Generated by Django 5.1.1 on 2025-03-14 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_plan'),
        ('User', '0034_usersub_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersub',
            name='plan_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.plan'),
        ),
        migrations.DeleteModel(
            name='Subcription',
        ),
    ]
